### ISSUE TITLE
Passing history in context to remember conversation

### ISSUE THREAD

**Issue by mohammad-yousuf** [snexus/llm-search#101]
Hi,

Is it possible to pass history in the context for the model to remember and trim the history according to context length?

**Comment by snexus** [comment]
Keeping conversational history isn't an easy problem with RAGs. I will explore how to implement this

**Comment by snexus** [comment]
I've created an initial implementation in the feature branched here - https://github.com/snexus/llm-search/tree/feature-conversation-history
The chat history length is adjustable via UI (to have enough space for the context). 

Please try it out, before merging to main.
