### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by bbecausereasonss** [snexus/llm-search#48]
Is this compatible with Windows 11, and CUDA 11.8?

**Comment by ImVexed** [comment]
Ditto, when using the `pdf_library.yaml` template after activating and installing all deps, the splitter seems to find no files in any of the `doc_path`'s provided. Not sure if this is a windows thing, as the docs seem to only reference linux.

**Comment by ImVexed** [comment]
nvm, was a bug in the code: https://github.com/snexus/llm-search/issues/50

**Comment by snexus** [comment]
CUDA 11.8 shouldn't be a problem. Also fixed the compatibility with Python 3.11. Please open a new ticket if you encounter a specific problem.
