### ISSUE TITLE
Support for .org files?

### ISSUE THREAD

**Issue by nightscape** [snexus/llm-search#49]
Thanks for writing and extensively explaining this project on Reddit!
I am a LogSeq user and have all my files in `.org` format.
I contributed an org parser for unstructured a while ago.
Would this project automatically support org through unstructured, or does sth. else need to be done (e.g. adding `.org` to some whitelist)?

Thank you!

**Comment by snexus** [comment]
It should be relatively easy to add. Can you point me to some examples of .org files?

**Comment by snexus** [comment]
Support added in 0.6.2
