### ISSUE TITLE
Repository Not Found for url:https://huggingface.co/api/models/infloat/e5-large-v2

### ISSUE THREAD

**Issue by dustinchen93** [snexus/llm-search#64]
After installation, I run command `llmsearch index create -c /path/to/config.yaml` to create vector db from local documents.  I got the following error.

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
`huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6545a903-603ca58107038257355ef890;303ff9ff-61b3-4505-9375-10ff6e1b6b6a)

Repository Not Found for url: https://huggingface.co/api/models/infloat/e5-large-v2.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.`

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
I tried BAAI/bge-large-en-v1.5 and this work fine.

**Comment by snexus** [comment]
Hi, 

Just tested it - the model was downloaded successfully without errors. It looks like a typo in the configuration - `infloat` vs `intfloat`. Please let me know if it fixes the issue.

**Comment by snexus** [comment]
Please re-open if the issue still persists.

**Comment by 4entertainment** [comment]
Hi, 
I edited my "llm-search/sample_templates/generic/config_template.yaml" code. I want to run "llmsearch index create -c /mypath" command. When i run this command i get the following output:
llmsearch: command not found
How did you do "installation part"?
