### ISSUE TITLE
Generate embeddings with CPU only

### ISSUE THREAD

**Issue by vulcano9** [snexus/llm-search#80]
Hi @snexus,

Thank you for your support and patient response to my (beginner) questions. I truly appreciate your assistance.

I don't have a dedicated graphics card, but I am eager to create the embeddings. 
Is there a way to achieve this without one (Google Colab unfortunately crashes after a certain period of time while creating embeddings with ~13000 chunks)? 

Thank you again for your support and I look forward to hearing from you.

**Comment by snexus** [comment]
Hi @vulcano9 

Without GPU, it would take a few orders of magnitude longer (technically I didn't test it - but should be supported out of the box on a system without GPU).

If you need only the embeddings, Google Colab should be able to handle it. What is the error message? How many documents and what format/size are you trying to parse?

**Comment by snexus** [comment]
Closing as stale issue
