### ISSUE TITLE
Support openai for Embedding

### ISSUE THREAD

**Issue by shuther** [snexus/llm-search#84]
Would it be possible to add OpenAIEmbeddings as a new possibility? It would help to leverage other self hosted embeddings when we couple it with litellm. If needed, I can create a PR.

**Comment by snexus** [comment]
Thanks for the suggestion, sounds like a good idea, please feel free to create a PR

**Comment by zhoumengbo** [comment]
Is it supported now?

**Comment by zhoumengbo** [comment]
@snexus We want to use OpenAI's embedding model for testing. How can we modify the source code to achieve this?

**Comment by snexus** [comment]
Hi, I will investigate and try to add support in the upcoming minor release, during the week.

**Comment by snexus** [comment]
Version 0.8.3 should support OpenAI's embeddings now. Here is an example configuration - https://github.com/snexus/llm-search/blob/main/sample_templates/openai_embeddings.yaml

Let me know if you have any issues.
