### ISSUE TITLE
update requirements.txt legacy langchain, chroma, openai

### ISSUE THREAD

**Issue by shuther** [snexus/llm-search#86]
The project sounds great, I am just unable to test it as I would like to.
I am hitting some bugs with some dependencies, and I am unable to upgrade the packages to get them fixed.
There is a chroma redesign ([chroma migration](https://docs.trychroma.com/migration#migration-to-0416---november-7-2023) with openai (v1.x) redesigned).
Is this project still maintained? if yes, is there a willingness to upgrade the requirements/code to support langchain>=0.10 ?

**Comment by snexus** [comment]
Yes, I will need to migrate it to the new versions (the changes are happening so fast). Will try to get to it during the weekend. It will require some work and testing.

What is breaking with the old dependencies? Is it the new OpenAI api?
