### ISSUE TITLE
support for cpp and hpp source code search? Generic text search?

### ISSUE THREAD

**Issue by bradphelan** [snexus/llm-search#90]
I'd like to try and get this to search my source code.

**Comment by snexus** [comment]
Hi, 

Currently, there is no special mode for source files, but it can be parsed as a regular text file. I believe it won't be optimal, but you are welcome to try.

**Comment by bradphelan** [comment]
When I add hpp and cpp files to the config file it reports an error message
saying that such files are not supported.

**Comment by snexus** [comment]
You are right, my bad, it has a restriction on available formats at the moment (the only native textual format supported is markdown). Here are all supported formats for the current version - https://github.com/snexus/llm-search/blob/5243360d90254385541f72137f41e27c4e7461b3/src/llmsearch/config.py#L40

It should be easy to extend, as unstructured.io supports source files nowadays, see here - https://unstructured-io.github.io/unstructured/core/partition.html

Will add it as an enhancement...

**Comment by snexus** [comment]
Support added in 0.6.2

**Comment by nh2** [comment]
@snexus What config does one need to use for general files with `unstructured`, e.g. with `.cpp` from the question here?
