### ISSUE TITLE
Feature request: Adding Llamaparse support for unstructured PDFs

### ISSUE THREAD

**Issue by mohammad-yousuf** [snexus/llm-search#99]
Hi,

Can you please add support support of Llamaparse for PDF parsing as it is really good at fetching important data from PDFs.

Thank you!

**Comment by snexus** [comment]
Hi,

Apparently LlamaParse is a paid service (they have a free option for a limited time), and it is not clear what is their future usage terms will be. Suggest to wait to get more clarity...

**Comment by snexus** [comment]
Closing this as unlikely I will implement it given the nature of LlamaParse. I might explore other options to increase the quality of parsing for PDFs, as it is a common problem.
